var nam = Number('991.33')
console.log(nam)
console.log(Number.parseInt(nam))
console.log(Number.MAX_VALUE)
console.log(Number.MIN_VALUE)
console.log(Number.MAX_SAFE_INTEGER)
console.log(Number.MIN_SAFE_INTEGER)
console.log(43753759035/0)
console.log('cc' * 22)